services:
  db_auth:
    image: postgres:16-alpine
    container_name: musica_db_auth
    environment:
      POSTGRES_DB: musica_db
      POSTGRES_USER: musica_user
      POSTGRES_PASSWORD: musica_pass
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musica_user -d musica_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  db_mysql:
    image: mysql:8.4
    container_name: musica_db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: musica_artista_db
      MYSQL_USER: artista_user
      MYSQL_PASSWORD: artista_pass
    volumes:
      - ./DbMysql/data:/var/lib/mysql
      - ./DbMysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  auth:
    build:
      context: ./auth
    container_name: musica_auth
    environment:
      DB_HOST: db_auth
      DB_PORT: 5432
      DB_NAME: musica_db
      DB_USER: musica_user
      DB_PASSWORD: musica_pass
    ports:
      - "8001:8001"
    depends_on:
      db_auth:
        condition: service_healthy

  artista:
    build:
      context: ./artista
    container_name: musica_artista
    restart: on-failure
    environment:
      MYSQL_HOST: db_mysql
      MYSQL_PORT: 3306
      MYSQL_DB: musica_artista_db
      MYSQL_USER: artista_user
      MYSQL_PASSWORD: artista_pass
    ports:
      - "8002:8002"
    depends_on:
      db_mysql:
        condition: service_healthy
      auth:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    container_name: musica_frontend
    ports:
      - "4200:4200"
    depends_on:
      auth:
        condition: service_started
      artista:
        condition: service_started
